# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bee9d808c302b0b169871b23de5d979b"
name = "popify"
handle = "popify-3"
application_url = "https://masters-attractions-controlled-overnight.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "anotherzopify.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://masters-attractions-controlled-overnight.trycloudflare.com/auth/callback",
  "https://masters-attractions-controlled-overnight.trycloudflare.com/auth/shopify/callback",
  "https://masters-attractions-controlled-overnight.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
